### ISSUE TITLE
environment variable might be useless

### ISSUE THREAD

**Issue by kenchris** [w3c/device-posture#11]
It is hard to know what type to use for the environment variable.

<angle> seems to make a lot of sense, and that can be used with something like `transform: skew(90deg)` but I don't see how to convert that to say pixels for moving animations.

CSS `calc` can only divide and multiply with integer numbers and I don't see any way to convert `deg` to an integer or `<length>` value

**Comment by diekus** [comment]
I do think it makes a lot of sense to have this variable, specially for cases like this one: 
![image](https://user-images.githubusercontent.com/3104648/86020201-810bad00-ba1f-11ea-8165-43e204224c49.png)

Indeed since it is an angle value, it is better suited for transforms (2D and 3D).

I also think there are simple ways of transferring this value to an angle to a length, specially in hands of developers the idea of normalizing this value would allow to achieve the desired effects regarding 'length'.

**Comment by LeaVerou** [comment]
> CSS `calc` can only divide and multiply with integer numbers and I don't see any way to convert `deg` to an integer or `<length>` value

Actually, recent changes to [css-values] made `calc()` able to divide with dimension values, see [this note](https://www.w3.org/TR/css-values/#ref-for-integer-value%E2%91%A0%E2%91%A0). We are just waiting for implementations.

**Comment by kenchris** [comment]
Closing as this is not part of the spec anymore
