### ISSUE TITLE
Supporting asymmetric shaped displays

### ISSUE THREAD

**Issue by chris480** [w3c/device-posture#37]
Going off the proposal I'm wondering how the current spec could handle multiple displays that aren't direct mirrors of each other. Such as a slide out display or a displays with different orientation from the parent (eg. the lg wing concept).

Some questions:
* Can the posture queries be chained to target a specific display?
* Are viewports returned per 'screen'?
* Does the spec address scroll behavior to allow independent scrolling windows?

**Comment by darktears** [comment]
The current Viewport Segments specification handles asymmetric segments, as well as more than two.

There seems to be a misconception in this issue. Device Posture and Viewport Segments are per browser window. For the viewport segments to be defined one needs to have the browser window spanning across both screens for example. See https://github.com/foldable-devices/demos.

I'm going to close this issue since it doesn't pertain to the Device Posture API anyway.
