### ISSUE TITLE
Fold Angle fingerprinting concerns and its usefulness

### ISSUE THREAD

**Issue by darktears** [w3c/device-posture#45]
Thread in blink-dev: https://groups.google.com/a/chromium.org/g/blink-dev/c/prHGPxF62i4

"First, we’re concerned about the fold.angle property, as that seems a high entropy fingerprinting surface. The specification mentions this, but leaves it to the implementer and does not touch on the level of precision and anonymization the API is trying to achieve. (The suggestions of lowering resolution and fuzzing are really two strategies for the same thing.)"

"Do you have specific use cases that need the full angle information? The spec has an example of angle-driven animations, but that already seems incompatible with the resolution/fuzzing mitigation it suggests. It seems this could use more exploration into use cases and how to balance them with privacy requirements."

**Comment by darktears** [comment]
@lauramorinigo @diekus can you guys expand on the fold angle property usefulness (beside that animation example in the spec). Did Samsung do any research on UX that would require exposing the fold angle in addition of the posture?

**Comment by kenchris** [comment]
It might also make sense to not expose the angle change for all values, like when the device is mostly closed and the user cannot see the change anyway.

**Comment by lauramorinigo** [comment]
There's no formal study that would require exposing the fold angle, therefore, our suggestions are:
- removing the angle: just using the posture will still satisfy most use case scenarios. The only ones which should take an angle as input are rotation transforms and CSS gradients.
- use an attribute in between postures to have a better idea of the angle and mitigate the issue, like from laptop to flat (suggested by  @PicchiKevin)

**Comment by diekus** [comment]
I'm not a fan of the idea of removing the angle. Apart from **animations**, it can be useful to be able to **specify** angles where the developers want the **break** or change to happen. Angles can also help **define ranges out of the predefined postures**. Devices have very different sizes and form factors to just rely on a posture. I do like Kenneth's idea of limiting the area where changes can be visible since there doesn't seem to be any major change for creative uses of the API, but I understand it doesn't fully cover the issue at hand .

Having said that I'm not super keen on Samsung's suggestions and maybe it'd make sense to suggest working on some UX research that Alexis mentioned? More than happy to brainstorm with Laura and Kenneth looking for use cases that might require these angles-- or eventually find out that maybe they're useless (still highly doubt this).

**Comment by beaufortfrancois** [comment]
@diekus Can you share real-life examples (videos would be great)? I failed to find ones that take advantage of `angle`.

**Comment by LaszloGombos** [comment]
For the time being perhaps we can make the angle attribute optional. This would allow the implementation of the posture to progress as well as collecting feedback and experimentation on the angle attribute. It would also allow a privacy-conscious implementation not to implement the angle property.

**Comment by jyasskin** [comment]
A couple thoughts:

1. [Hiding the angle value for just almost-closed angles](https://github.com/w3c/screen-fold/issues/45#issuecomment-754554119) doesn't really help the ephemeral-fingerprinting issue, as the user isn't likely to be switching apps at that point anyway.
2. Making the angle optional just means that minority implementations have to either sacrifice compatibility or do extra work to reverse-engineer the behavior of the more-widely-used implementation(s). It doesn't solve the problem for any implementation that actually provides [`angle`](https://w3c.github.io/screen-fold/#dom-screenfold-angle).
3. Omitting `angle` from the main spec would let `posture` ship when it's ready, and y'all could still have a side spec that defines `angle` and goes through the origin trial process concurrently.
4. It seems like a burden to ask developers to find the angles that work best for breaks. To the extent we can do that for developers, we should. If that means adding a couple more postures, or defining that angles get quantized to a set of 4-8 values, maybe with devices able to adjust the exact bounds of the quantization ranges, that seems reasonable.

**Comment by kenchris** [comment]
Generally a user isn't generally switching apps while changing the fold angle. You of course could by mistake, but that could be mitigated by waiting a few angle changes before sending these events to a newly focused web site.

> It seems like a burden to ask developers to find the angles that work best for breaks. To the extent we can do that for developers, we should. If that means adding a couple more postures, or defining that angles get quantized to a set of 4-8 values, maybe with devices able to adjust the exact bounds of the quantization ranges, that seems reasonable.

That is also the feedback that I have from my Intel colleagues and OEMs - we really don't want users to do this manually.

**Comment by darktears** [comment]
> That is also the feedback that I have from my Intel colleagues and OEMs - we really don't want users to do this manually.

To give a bit of color here, in the future the posture may not be determined just by the angle of the hinge, but other set of factors and a conjunction of sensors. I fully expect that down the road the posture determination will happen at the OS level so it's consistent between apps/app ecosystems and would let opportunity for lower level components to compute the posture (e.g. sensor hubs). 

So we definitively don't want developers to start computing their own postures or decide the breaks because the user expectation (in terms of window management, virtual/physical keyboard) would not match what they typically encounter while using the device. Let's give a practical example, the X1 Fold has a detachable magnetic keyboard, if the device is half folded and the keyboard is attached or detached the entire UX/OS reacts to it though the fold angle hasn't changed, yet the user will expect the website to react.

**Comment by jyasskin** [comment]
@darktears It sounds like you agree that we should omit `angle` from the initial version of the API, so that developers get used to relying on `posture` instead of writing their own breakpoints?

It sounds like the animation use case could use some more experimentation for the best way to do it, and maybe its own origin trial? @kenchris' suggestion that we hide the angle from a switched-to page until the user has changed the angle enough to cross a quantized boundary: would allow animations, prevent devs from using it instead of `posture`, and avoid the ephemeral-fingerprinting problem; but it could also use some checking that developers can actually use it well.

**Comment by darktears** [comment]
@jyasskin I think we should bring it to the origin trial experiment thinking as we would ship it one day, then depending on developer feedback we can just keep it or remove the bindings. That's what Origin Trial are for.

If we decide to remove it (after the trial) and developers want it down the road, we can always add it later, but we must keep in mind that the hinge angle is accessible through the native APIs so native developers, see https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors.hingeanglesensor?view=winrt-19041 or https://developer.android.com/reference/android/hardware/Sensor#STRING_TYPE_HINGE_ANGLE

**Comment by davidben** [comment]
Origin trials still need to meet the usual security and privacy requirements. That story is much clearer for `posture` than `angle`, so sticking to `posture` initially will avoid blocking it on resolving the issues with `angle`. It sounds like `posture` is the preferred API for most fold-related use cases anyway, so this seems a clear decision.

While the angle may be exposed via native APIs, the web platform has its own security and privacy model, so related use cases may ultimately require different solutions.

**Comment by torgo** [comment]
We think that enabling animated transitions in UI is a very valid use case that is a common approach taken in many scenarios. We're also basing this on existing implementation for native apps that have been redesigned for folding screens - for example, a camera application that 'explains' what is happening with the UI by animating the transition from full-screen UI to a version of that UI that makes more sense when the device is folded into 'laptop' posture.

It may not, however, be necessary to have access to the exact angle of the fold in order to accomplish this task. Quantization of values, as @jyasskin suggested, could do the trick, for example.

**Comment by kenchris** [comment]
We also think it is a valid use-case, but we are considering making it part of "Window Segments" API as discussed in yesterday's Second Screen WG meeting. We are going to see devices with more than one fold and for that reason it is important to be able to associate an angle with the right folding hinge and know its position, viewport wise (which is why it is a good match with Window Segments) @darktears @anssiko @beaufortfrancois

**Comment by davidben** [comment]
It seems to me that `posture` would be sufficient for typical animations and we don't need `angle`. Many mobile devices today have landscape and portrait orientations, and successfully explain the situation to users with a rotation animation. That animation is not typically driven by the phone's intermediate orientation, but just triggered when the mode switches. Transitions from `posture` modes could do the same thing. I would continue to recommend starting with `posture` and seeing what developers manage with it.

Also note that the bar for shipping APIs in the platform is two-fold: it must have a valid use case *and* it must meet security and privacy requirements. The issue here is that the `angle` does not meet the second requirement due to fingerprinting risk. Uses cases alone don't clear that requirement. (I did ask for use cases in my original email, but it was to suggest you all explore other paths: when one solution doesn't pan out, it helps to clarify the problem when looking for new solutions.)

Regarding quantization, that is a possible mitigation, though it is not a silver bullet. Quantization mitigates fingerprinting only as much as the information is reduced. Quantize too much, and the API may no longer meet use cases. Quantize too little and the API does not cleared the security/privacy bar.

For example,`posture` is itself a quantization. It's an especially compelling one because it maximizes usefulness by picking points in the space with clear semantics, which lets it survive a much harsher quantization. Thus I again suggest that is a better starting point and to defer `angle`.

**Comment by lauramorinigo** [comment]
In order to keep moving on this, even though the best scenario is to keep the original spec, we rather remove the angle and focus on posture implementing this with window segments API.
